"""empty message

Revision ID: 87a07e73729d
Revises: 
Create Date: 2020-01-25 13:54:32.272946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a07e73729d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletics',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_type', sa.String(length=50), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('noc', sa.Boolean(), nullable=False),
    sa.Column('amt_paid', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('karate',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_type', sa.String(length=50), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('noc', sa.Boolean(), nullable=False),
    sa.Column('amt_paid', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('yoga',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_type', sa.String(length=50), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('noc', sa.Boolean(), nullable=False),
    sa.Column('amt_paid', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yoga')
    op.drop_table('karate')
    op.drop_table('athletics')
    # ### end Alembic commands ###
