"""empty message

Revision ID: 9db8ae6f08dc
Revises: 87a07e73729d
Create Date: 2020-01-25 15:47:51.442926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9db8ae6f08dc'
down_revision = '87a07e73729d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'branch')
    op.drop_column('competitors', 'gender')
    op.drop_column('competitors', 'father_name')
    op.drop_column('competitors', 'year')
    op.drop_column('competitors', 'college')
    op.drop_column('tempcompetitors', 'branch')
    op.drop_column('tempcompetitors', 'gender')
    op.drop_column('tempcompetitors', 'father_name')
    op.drop_column('tempcompetitors', 'year')
    op.drop_column('tempcompetitors', 'college')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tempcompetitors', sa.Column('college', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('tempcompetitors', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tempcompetitors', sa.Column('father_name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('tempcompetitors', sa.Column('gender', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('tempcompetitors', sa.Column('branch', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('competitors', sa.Column('college', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('competitors', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('competitors', sa.Column('father_name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('competitors', sa.Column('gender', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('competitors', sa.Column('branch', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
