"""empty message

Revision ID: 9f38ec01e0a9
Revises: 9db8ae6f08dc
Create Date: 2020-01-25 15:48:47.244450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f38ec01e0a9'
down_revision = '9db8ae6f08dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('college', sa.String(length=200), nullable=False))
    op.add_column('tempcompetitors', sa.Column('college', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tempcompetitors', 'college')
    op.drop_column('competitors', 'college')
    # ### end Alembic commands ###
