eventdetailsEn={
"Basketball":{"max":12,"min":5,"stu_co":"DIVYANSHU KAUSHIK","stu_co_contact":"9455617249-","teach_co":"SMARIKA SINGH","amount":" Boys:Rs.3000-Girls:Rs.3000","types":"TeamEvent",
"rules":"MEN-Number of players maximum:12 minimum:5 –WOMEN- Maximum players: 12 minimum: 5-All the playing rules will be according to FIBA.-The refree’s decision will be final.-The teams are required to report 30 min before given time.-College/Institute ID card is mandatory with one Government Id proof."
},
"Carrom":{"max":7,"min":5,"stu_co":"Saurav Tomar","stu_co_contact":"8218053564-","teach_co":"-","amount":"Team:Rs.1500","types":"TeamEvent",
"rules":" Team game will be there.-3 singles and 2 doubles-1 player can play max 2 events.-Board of 29 points will be played containing 8 rounds.-Team with highest point will be winner. In case of a tie a deciding board will be played.-Also the team with highest board win will be winner in such a case.Back hand is allowed.-Rest All the Indian federation of Carrom rules will be followed.-Decision of referee will be final"
},
"Football":{
"max":16,"min":11,"stu_co":"ROHIT SRIVASTAVA","stu_co_contact":"8887916925-","teach_co":"-","amount":"Boys:Rs.3000-Girls:Rs.3000","types":"TeamEvent",
"rules":"Every team can have maximum of 16 players (11+5) and minimum of 11 players for boys and maximum of 9 players (7+3) and minimum of 7 players for girls.-The Referee’s decision is final and no argument should be done. Else the player or team will be penalized as the referee will think right to do.-Any misconduct on the field can lead to disqualification of the team.-Other rules regarding the match will be told on the field.-The above rules are applicable on both girls and boys football team.-All players are to honor the game rules and play in healthy competition."
},
"Cricket":{"min":12,"max":15,"stu_co":"ANUJ KAMAT","stu_co_contact":"9870832997-8604357522","teach_co":"PAWANDEEP YADAV","amount":"Team:Rs.3000","types":"TeamEvent",
"rules":"Every team can have maximum of 15 players  (playing 11 + 4 extra).-The Team Captain is responsible for informing all of the teammates about when the team will be playing and on what dates. Our responsibility is to tell the Captain when his team will be playing.-Every team should be well dressed and shoes are compulsory in tournament.-During the power play, a maximum of 2  fielders should be outside the fielding circle.-Teams should report 30 minutes before the start of the play.-After the toss, the fielding team should set the fielding positions immediately to avoid any delay to begin the match. Batsmen will come to the crease only after the field arrangement.-Organizing committee will reserve full authority to intervene in such case off field and umpires will have full authority to intervene on field.Each captain should nominate his playing XI before the toss.- No player can be changed after the nomination without the consent of the opposing captain.-A new ball will be provided for each innings. In case of loss or damaged ball, umpire will replace the old ball with a new one/replacement ball and dead ball will give in case of out only. (Run out will not consider)-Umpires decisions will be final throughout the tournament. Any sort of misconducts by any players will result in direct suspension.-Organizers reserve the right to change the venue, date time and reduce the overs of matches at short notice.-A team must be ready to play two matches in a day, if required.-Substitute runners are not allowed, unless a batsman gets injured in the field during a particular match and the role of a substitute will be fielding only.-No Duckworth–Lewis method is applied for weather affected matches. Umpires will take the final decision to stop the match.-If any player have any query regarding boundary or about any rule he can directly contact to umpires or organizers before the match."
},
"Volleyball":{"min":6,"max":12,"stu_co":"Badal Singh","stu_co_contact":"9870945302-","teach_co":"","amount":"Boys:Rs.3000-Girls:Rs.3000","types":"TeamEvent",
"rules":" Maximum Members : Boys:= 12  Girls:=10.-Match Of Three Set Of 25 Points Each.-Final Will Be Of 5 Sets.-League/Knockout Match (Depends Upon The Number Of Entries).-Team Have To Be Present On Court 15 Minutes Prior To Match.-Referee Decision is Considered To Be Final.-General Volleyball Rules.-Failure In Any Above Will Lead To Disqualification."
},
"Pool":{"min":1,"max":2,"stu_co":"Nitesh Kumar","stu_co_contact":"8958781393-8960651955","teach_co":"AKSHAY AGARWAL","amount":"Single:Rs.300-Double:Rs.600-Mixed:Rs.600","types":"Single-Double-MixedDouble",
"rules":"Break shot will be decided by the toss.-During break if black ball gets pot than it is considered to be the golden break.-For a break to be a legal one is required that minimum 4 balls should touch the side cushion .-For a legal shot any ball after contact with some other ball must touch any of the side cushion .-Jump shots are foul.-Any king of foul by an opponent will result in ball in hand opportunity for the other opponent.-Decision of the match Referee will be final.-Any argument or misbehaviour with Referee as well as players may lead to disqualification of the respective team or an individual person.-All players are required to maintain the dignity and respect of the game as well as of other players."
},
"Badminton":{"min":4,"max":7,"stu_co":"MUKUND AGARWAL","stu_co_contact":"8057332428-","teach_co":"-","amount":"Boys:Rs.2000-Girls:Rs.1000-Mixed:Rs.600","types":"MixedDouble-TeamEvent",
"rules":" All players must wear non-marking shoes.- All the rules and standards  are according to BAI (Badminton Association of India).-Boys:-Team size: 4+3 .-Tournament will be conducted in knockout/ league format .-Each match is best of 3 set of 21/15 points each, according to the number of teams.- GIRLS:-Team size: 2+2 .-Tournament will be conducted in knockout /league format.-Each match is  best of 3 sets of 21/15 points  each, according to the number of teams.-MIXED DOUBLES:-It will be conducted in knockout/league format.-Each match is best of 3 sets of 21/15 points each, according to the number of teams."
},

"Tabletennis":{"min":1,"max":4,"stu_co":"Vaibhav","stu_co_contact":"8126372925-","teach_co":"-","amount":"Singles:Rs.300-Team:Rs.1200","types":"Single-TeamEvent",
"rules":"There will the two events in the tournament in both boys and girls – Singles.-There will also be a Team Event.-For the events, this is an individual player registration sport.-Each match will have three sets of 11 points each.-Best of the three sets will decide the winner.-If the player fails to report the venue 15 minutes before the game, the opponent shall be given a win.-In any case, referee’s decision will be final."
},
"Lawntennis":{"min":1,"max":1,"stu_co":"NITESH KUMAR ","stu_co_contact":"8005366011-8006504488","teach_co":"-","amount":"Single:Rs.300","types":"Singles",
"rules":"Men: This will be an individual event.-Women : This will  be an individual event.- The no. of players representing any college in a team can be maximum of 1 members.-All matches will be of one set each-Tie will be enforced at 6 all-All ATP rules will be followed-Foul calls will be subject to linesman call-Any new rule or change in rules will be informed to the teams by the event coordinators prior to the beginning of match. In any case, the decision of referee and the officials shall be considered final.-In case of discrepancy, the decision of referees shall be considered final.-Late reporting may lead to disqualification."
},
"Chess":{"min":4,"max":5,"stu_co":"ASHISH GUPTA ","stu_co_contact":"8077700468-","teach_co":"-","amount":"Team:Rs.1200-Single:Rs.300","types":"Single-TeamEvent",
"rules":"Team event :-1. The team comprises of 4 playing members and  maximum 5 members. (4+1).-2. The event will be played in a league format.-3. A player gets 1 point on win, 0.5 on draw and 0 on losing a game.-4. All FIDE rules will be followed.-5. The time limit will be 25 min+10 sec  on each side.-6. Mixed team of boys and girls are allowed.-Individual event : -1. No. of rounds will depend upon no. of participating players.-2. The time limit will be 25 min+10 sec  on both sides. -3. A player gets 1 point on win, 0.5 on draw and 0 on losing a game.-4. All FIDE rules will be followed."
},
"Pubg":{"min":4,"max":4,"stu_co":"Rishabh Singh ","stu_co_contact":"7906065912-8004367336","teach_co":"-","amount":"Team:Rs.200","types":"TeamEvent",
"rules":"Make sure to grab the match Id and password before the match start time.-Make sure you join the room ASAP before the match starts otherwise, we won't be responsible for it and no refund in such case.-Match will start after 15 minutes of sharing room ID and password.-Don’t share match ID and password with anyone else who has not registered for match, if found so you will be disqualified.-Teaming is against game rules.-Last standing man’s squad gets the Chicken Dinner award.-Players need to bring their own gaming devices.-Less than four members are allowed in a squad.-The entry fees is for squad only.-While registration  Pubg  ID and playing media (i.e. mobile ) of every member of squad must be mentioned.-Do not use any hacks.-If anyone found violating these rules then immediate action will be taken and whole squad will be disqualified and rewards may be abandoned."
},
"Fifa":{"min":1,"max":1,"stu_co":" Rishabh  ","stu_co_contact":"9519520017-8630319945","teach_co":"-","amount":"Single:Rs.100","types":"Single",
"rules":"Game Tactics: Custom tactics allowed-Formations: Allowed-Injuries: Off-Referee: Random-Half Length: 5 minutes-Handball: Off-Weather: Clear-Season: Summer-FIFA Trainer: Off-Keeper Difficulty:legendary-Final decision would be our.-All matches would be knockout."
},
"Karate":{"max":1,"min":1,"stu_co":"HARSHIT SAXENA","stu_co_contact":"8948301408-","teach_co":"-","amount":"INDIVIDUAL:Rs.300","types":"Single",
"rules":" AS PER RULES GIVEN BY KARATE ASSOCIATION OF INDIA(KAI).-The refree’s decision will be final.-The teams are required to report 30 min before given time.-College/Institute ID card is mandatory with one Government Id proof."
},
"Athletics":{"max":1,"min":1,"stu_co":"ADITYA RAO","stu_co_contact":"7071232371-","teach_co":"-","amount":"INDIVIDUAL: Boys:Rs.200-Girls:Rs.200","types":"Single",
"rules":" EVENTS-100M, 200M, 400M, 800M, 1500M, 3000M.-Shot Put Rules:-Once the athlete’s name is called, they have 60 seconds to release the shot.-The shot must be placed close to the neck and resting on the shoulder, while keeping it in that position the entire time until it is released. -No padding or extra equipment is necessary.-The shot must be released above the height of the shoulder with one hand.-The athlete is permitted to touch the inside surface of the stop board; however neither the top nor the outside of the circle or stop board can be touched or passed.-The shot is required to land within the legal sector (34.92°).-The competitor must exit the circle from the back.-LONG JUMP RULES:-All rules for long jump are made and monitored through International Association for Athletic Federations.-Playing by rules will fetch you points on your performance and the reverse may cost you penalty which may lead to disqualification from the entire tournament.-.-The referee’s decision will be final.-The teams are required to report 30 min before given time.-College/Institute ID card is mandatory with one Government Id proof."
},
"Yoga":{"max":1,"min":1,"stu_co":"KRISHNA KUMAR","stu_co_contact":"8932920363-","teach_co":"-","amount":"INDIVIDUAL:Rs.300","types":"Single",
'rules':"All rules for YOGA are made and monitored through YOGA FEDERATION OF INDIA.Playing by rules will fetch you points on your performance and the reverse may cost you penalty which may lead to disqualification from the entire tournament.INDIA.-Playing by rules will fetch you points on your performance and the reverse may cost you penalty which may lead to disqualification from the entire tournament.--The referee’s decision will be final.-The teams are required to report 30 min before given time.-College/Institute ID card is mandatory with one Government Id proof." }}
